### ISSUE TITLE
environmental-orgs fetch needs separately stored credentials file

### ISSUE THREAD

**Issue by jasonmoofang** [climatecabinet/ec2-deployment-test#3]
Not necessarily an "issue" but thought I'd make a note of this here. Perhaps this ought to be in the Readme?

"Unable to locate credentials file needed to run this function. If this is your 
first time running the script, you'll need to download the 'credential.json' file 
from the Climate Cabinet password management vault before proceeding. Reach out 
to a CliCab admin for access and help making this happen. Once this file is 
downloaded, please put it in the following location"

At any rate also noting that I don't currently have credentials so I can't actually test fetch for environmental-orgs :)

**Comment by mherrero347** [comment]
Good note! I actually think this is desirable behavior for now, just directing the user to reach out to an admin if they need to run privileged functionality. I can send you the credentials for this and we can test it!
